name: 'Run Tests'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install dependencies
        run: |
          go version
          go get ./...
      - name: Run build
        run: |
          go build -o bin/main
      - name: Run tests
        run: |
          go test -v ./...
  push_to_hub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Extract Release Version
        run: echo "RELEASE VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log in to the Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nekinci/spg:${{ env.RELEASE_VERSION }}
