name: Publish Docker Image
on:
  push:
    tags:
      - '*'

jobs:
  push_to_hub:
    environment: OSS
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: nekinci/spg
      - name: Log in to the Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nekinci/spg:${{ steps.meta.outputs.tags }}
          labels: nekinci/spg:${{ steps.meta.outputs.labels }}
